### PR TITLE
Added Sponsorship Logos, Fixed Table of Sponsor Logos, Deleted Old Logos (see google drive for high res ones)

### PR DESCRIPTION
**Pull request by koronkowy**

### CODE REVIEW

**Comment by koronkowy** [comment]
This should fix the issue that @securelyfitz mentioned about centering the sponsorship logos, FYI.

**Comment by tophertimzen** [comment]
There are blank entries in rows in the middle of some sponsors tables when this gets rendered, example being

```
A10     | ^H
        | Intel
Mozilla |  NETSPI
```

Can you adjust the tables on sponsors.md to have everything left aligned, and if there is a blank logo slot put it on the right side on the last row?

This happens in Platinum and Gold. (for gold the left blank row is before incomm)

You can see how this will get rendered by doing a local jekyll build, https://github.com/BSidesPDX/bsidespdx.org/wiki/Development

**Comment by tophertimzen** [comment]
Ah, the issue might be something else actually.

```
[2018-10-06 10:01:52] ERROR `/images/2018/web-logos/hackerone.png' not found.
[2018-10-06 10:01:52] ERROR `/images/2018/web-logos/symantec.png' not found.
[2018-10-06 10:01:52] ERROR `/images/2018/web-logos/bpm.png' not found.
[2018-10-06 10:01:52] ERROR `/images/2018/web-logos/twilio.png' not found.
[2018-10-06 10:01:52] ERROR `/images/2018/web-logos/summit.png' not found.

```

A few of these file paths are wrong; for example `hackerone.png` is `HackerOne.png` in the images directory but is being referenced as `/images/2018/web-logos/hackerone.png` in `sponsors.md`

**Comment by koronkowy** [comment]
Ugh, yeah. Name reverted at one point and the lowercase versions got changed. I fixed the files. Let me reupload.

**Comment by koronkowy** [comment]
@tophertimzen Should be fixed now. Stupid mistake.

**Comment by tophertimzen** [comment]
Page now renders without any errors and the row issue described above is now fixed. I'll merge this PR into master.

**Pull request merged**
